version: "3"
services: #docker run --restart=always --name mysql -p 3306:3306 -p 33060:33060 -v ~/DockerVolumes/mysql:/var/lib/mysql -d mysql:8.0.20
  mysql:
    image: mysql:8.0.20
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - "~/DockerVolumes/mysql:/var/lib/mysql"
  grpc-svc:
    image: hellojqk/grpc-svc:0.0.1
    ports:
      - "50051:50051"
    command:
      - "-mysqlhost=mysql"
    depends_on:
      - mysql
    links:
      - mysql:mysql
  grpc-api:
    image: hellojqk/grpc-api:0.0.1
    ports:
      - "8081:8081"
    command:
      - "-grpc-svc=grpc-svc:50051"
    depends_on:
      - grpc-svc
    links:
      - grpc-svc
  grpc-web:
    image: hellojqk/grpc-web:0.0.1
    ports:
      - "8080:80"
    depends_on:
      - grpc-api
    links:
      - grpc-api
networks:
  elk:
    driver: bridge
