apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: default
  labels:
    environment: test
    app: hello
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      initContainers:
        - name: init-container
          image: hellojqk/alpine:3.10.1
          command: ["echo"," 我随便写一个文件 >> a.txt"]
      containers:
      - name: helloworld
        image: hellojqk/helloworld:latest
        resources:
          limits:
            memory: "80Mi"
            cpu: "0.15"
          requests:
            memory: "40Mi"
            cpu: "0.1"
        args:
          - "-port"
          - "8888"
          - "-redis_ss"
          - "redis-srv-s.demo:6379"
          - "-redis_d"
          - "redis-srv-d.demo:6379"
        ports:
        - containerPort: 8888
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
                - "ls"
                - "-l"
      restartPolicy: Always
  revisionHistoryLimit: 10
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---

kind: Service
apiVersion: v1
metadata:
  name:  helloworld-srv
  namespace: default
  labels:
    environment: test
    app: hello
spec:
  selector:
    app:  helloworld
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port:  8888
    targetPort:  8888
    nodePort: 31112

---